// Hand-typed surface of the Lend Postgres schema, scoped to the
// entities Phase 2 actually reads/writes. We keep this narrow on purpose:
// once we have a stable Supabase project we can switch to types
// generated by `supabase gen types typescript`.
//
// Mirrors supabase/migrations/20260502120000_initial_schema.sql.

export type AppRole = 'customer' | 'merchant' | 'admin';
export type AccountStatus = 'pending' | 'active' | 'suspended';
export type MerchantApplicationStatus = 'pending' | 'approved' | 'rejected';
export type MerchantStatusDB = 'pending_review' | 'active' | 'suspended';
export type RentalCategoryDB = 'dress' | 'bag' | 'watch' | 'bisht';
export type EligibilityTier = 'standard' | 'premium' | 'elite';

export type LocalizedJson = { ar: string; en: string };

export type ProfileRow = {
  id: string;
  full_name: string;
  mobile: string | null;
  email: string | null;
  national_id: string | null;
  city: string | null;
  role: AppRole;
  account_status: AccountStatus;
  nafath_verified_at: string | null;
  // Phase 8e — first-class identity verification state. Customers
  // start as unverified and flip to verified inside the rental flow
  // (see record_identity_verification RPC).
  identity_verified: boolean;
  identity_verified_at: string | null;
  identity_provider: string | null;
  identity_reference_id: string | null;
  created_at: string;
  updated_at: string;
};
export type ProfileInsert = Partial<ProfileRow> & { id: string; full_name: string };
export type ProfileUpdate = Partial<ProfileRow>;

export type RentalEligibilityRow = {
  user_id: string;
  limit_amount: number;
  used_amount: number;
  tier: EligibilityTier;
  assigned_by: string | null;
  assigned_at: string;
  notes: string | null;
  updated_at: string;
};
export type RentalEligibilityInsert = Partial<RentalEligibilityRow> & {
  user_id: string;
};
export type RentalEligibilityUpdate = Partial<RentalEligibilityRow>;

export type MerchantRow = {
  id: string;
  owner_user_id: string;
  application_id: string | null;
  company_name: string;
  commercial_reg_number: string;
  display_name: LocalizedJson;
  about: LocalizedJson | null;
  primary_category: RentalCategoryDB;
  city: string;
  verified: boolean;
  rating: number;
  rating_count: number;
  status: MerchantStatusDB;
  approved_at: string | null;
  approved_by: string | null;
  created_at: string;
  updated_at: string;
};
export type MerchantInsert = Partial<MerchantRow> & {
  owner_user_id: string;
  company_name: string;
  commercial_reg_number: string;
  display_name: LocalizedJson;
  primary_category: RentalCategoryDB;
  city: string;
};
export type MerchantUpdate = Partial<MerchantRow>;

export type MerchantApplicationRow = {
  id: string;
  applicant_user_id: string;
  company_name: string;
  commercial_reg_number: string;
  authorized_name: string;
  authorized_national_id: string;
  city: string;
  primary_category: RentalCategoryDB;
  contact_email: string | null;
  contact_phone: string | null;
  notes: string | null;
  status: MerchantApplicationStatus;
  decided_by: string | null;
  decided_at: string | null;
  decision_notes: string | null;
  submitted_at: string;
  created_at: string;
  updated_at: string;
};
export type MerchantApplicationInsert = Omit<
  MerchantApplicationRow,
  | 'id'
  | 'status'
  | 'decided_by'
  | 'decided_at'
  | 'decision_notes'
  | 'submitted_at'
  | 'created_at'
  | 'updated_at'
> & {
  status?: MerchantApplicationStatus;
};
export type MerchantApplicationUpdate = Partial<MerchantApplicationRow>;

// ---------------------------------------------------------------------
// Rental document chain — invoices, items, contracts, notes
// ---------------------------------------------------------------------

export type InvoiceStatus =
  | 'draft'
  | 'issued'
  | 'viewed'
  | 'accepted'
  | 'rejected'
  | 'cancelled'
  | 'superseded';

export type ContractStatusDB = 'pending' | 'active' | 'ended' | 'cancelled';

export type NoteStatus = 'pending' | 'signed' | 'settled' | 'defaulted';

export type RentalInvoiceRow = {
  id: string;
  invoice_number: string;
  merchant_id: string;
  branch_id: string | null;
  customer_user_id: string;
  subtotal_amount: number;
  tax_amount: number;
  security_deposit: number;
  total_amount: number;
  /** The underlying value of the rented item. Drives eligibility holds
   *  + the promissory note principal. Distinct from total_amount, which
   *  is the rental fee charge. */
  original_item_value: number;
  /** Light damage fraction (0..1). Multiplied by the replacement
   *  value to give the partial-damage liability. Merchant-controlled
   *  in the contract preparation step; defaults to 0.300. */
  light_damage_fraction: number;
  /** Late return multiplier (×). Multiplied by the daily rate to give
   *  the per-day late-return fee. Merchant-controlled; defaults to
   *  1.50. */
  late_return_multiplier: number;
  status: InvoiceStatus;
  issued_at: string | null;
  expires_at: string | null;
  scan_token: string | null;
  notes: string | null;
  created_at: string;
  updated_at: string;
};
export type RentalInvoiceInsert = Partial<RentalInvoiceRow> & {
  invoice_number: string;
  merchant_id: string;
  customer_user_id: string;
};
export type RentalInvoiceUpdate = Partial<RentalInvoiceRow>;

export type RentalInvoiceItemRow = {
  id: string;
  invoice_id: string;
  position: number;
  item_name: string;
  category: RentalCategoryDB;
  size_label: string | null;
  color: string | null;
  daily_rate: number;
  rental_days: number;
  subtotal: number;
  replacement_value: number | null;
  notes: string | null;
  created_at: string;
};
export type RentalInvoiceItemInsert = Omit<RentalInvoiceItemRow, 'id' | 'created_at'> & {
  id?: string;
};
export type RentalInvoiceItemUpdate = Partial<RentalInvoiceItemRow>;

export type RentalContractRow = {
  id: string;
  contract_number: string;
  invoice_id: string;
  customer_user_id: string;
  merchant_id: string;
  branch_id: string | null;
  start_date: string;
  end_date: string;
  rental_fee_amount: number;
  security_deposit: number;
  total_amount: number;
  /** Mirrors rental_invoices.original_item_value at signing — drives
   *  the eligibility decrement on close and the note principal. */
  original_item_value: number;
  status: ContractStatusDB;
  signed_at: string | null;
  ended_at: string | null;
  nafath_verified_at: string | null;
  nafith_attested_at: string | null;
  /** Storage object key for the customer's handover photo, written by
   *  the record_contract_handover RPC after the customer captures it
   *  in the Contracts tab. NULL until handover happens. */
  handover_photo_path: string | null;
  handover_at: string | null;
  created_at: string;
  updated_at: string;
};
export type RentalContractInsert = Partial<RentalContractRow> & {
  contract_number: string;
  invoice_id: string;
  customer_user_id: string;
  merchant_id: string;
  start_date: string;
  end_date: string;
  rental_fee_amount: number;
  total_amount: number;
};
export type RentalContractUpdate = Partial<RentalContractRow>;

export type PromissoryNoteRow = {
  id: string;
  reference_number: string;
  contract_id: string;
  customer_user_id: string;
  merchant_id: string;
  beneficiary_name: string;
  principal_amount: number;
  due_date: string;
  status: NoteStatus;
  signed_at: string | null;
  settled_at: string | null;
  defaulted_at: string | null;
  nafith_attested_at: string | null;
  created_at: string;
  updated_at: string;
};
export type PromissoryNoteInsert = Partial<PromissoryNoteRow> & {
  reference_number: string;
  contract_id: string;
  customer_user_id: string;
  merchant_id: string;
  beneficiary_name: string;
  principal_amount: number;
  due_date: string;
};
export type PromissoryNoteUpdate = Partial<PromissoryNoteRow>;

// ---------------------------------------------------------------------
// Damage cases + evidence
// ---------------------------------------------------------------------

export type DamageSeverity = 'partial' | 'total' | 'non_return';
export type DamageStage    = 'review' | 'settlement' | 'nafith' | 'execution';
export type DamageStatus   = 'open' | 'settled' | 'escalated' | 'dismissed';
export type EvidenceType   = 'photo' | 'video' | 'document';

export type DamageCaseRow = {
  id: string;
  case_number: string;
  contract_id: string;
  customer_user_id: string;
  merchant_id: string;
  raised_by_user_id: string | null;
  severity: DamageSeverity;
  stage: DamageStage;
  status: DamageStatus;
  claim_amount: number;
  description: string;
  raised_at: string;
  resolved_at: string | null;
  resolved_by_user_id: string | null;
  resolution_notes: string | null;
  created_at: string;
  updated_at: string;
};
export type DamageCaseInsert = Partial<DamageCaseRow> & {
  case_number: string;
  contract_id: string;
  customer_user_id: string;
  merchant_id: string;
  severity: DamageSeverity;
  description: string;
};
export type DamageCaseUpdate = Partial<DamageCaseRow>;

export type DamageEvidenceRow = {
  id: string;
  case_id: string;
  evidence_type: EvidenceType;
  storage_path: string;
  caption: string | null;
  uploaded_by_user_id: string | null;
  uploaded_at: string;
};
export type DamageEvidenceInsert = Omit<DamageEvidenceRow, 'id' | 'uploaded_at'> & {
  id?: string;
};

// Minimal Database surface for typed supabase client. Add tables here as
// Phase 3+ wires in invoices, contracts, notes, damage cases, etc.
//
// Shape follows the GenericSchema contract from @supabase/postgrest-js
// (Tables/Views/Functions records, each table carrying Relationships).
export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: ProfileRow;
        Insert: ProfileInsert;
        Update: ProfileUpdate;
        Relationships: [];
      };
      rental_eligibility: {
        Row: RentalEligibilityRow;
        Insert: RentalEligibilityInsert;
        Update: RentalEligibilityUpdate;
        Relationships: [];
      };
      merchants: {
        Row: MerchantRow;
        Insert: MerchantInsert;
        Update: MerchantUpdate;
        Relationships: [];
      };
      merchant_applications: {
        Row: MerchantApplicationRow;
        Insert: MerchantApplicationInsert;
        Update: MerchantApplicationUpdate;
        Relationships: [];
      };
      rental_invoices: {
        Row: RentalInvoiceRow;
        Insert: RentalInvoiceInsert;
        Update: RentalInvoiceUpdate;
        Relationships: [];
      };
      rental_invoice_items: {
        Row: RentalInvoiceItemRow;
        Insert: RentalInvoiceItemInsert;
        Update: RentalInvoiceItemUpdate;
        Relationships: [];
      };
      rental_contracts: {
        Row: RentalContractRow;
        Insert: RentalContractInsert;
        Update: RentalContractUpdate;
        Relationships: [];
      };
      promissory_notes: {
        Row: PromissoryNoteRow;
        Insert: PromissoryNoteInsert;
        Update: PromissoryNoteUpdate;
        Relationships: [];
      };
      damage_cases: {
        Row: DamageCaseRow;
        Insert: DamageCaseInsert;
        Update: DamageCaseUpdate;
        Relationships: [];
      };
      damage_evidence: {
        Row: DamageEvidenceRow;
        Insert: DamageEvidenceInsert;
        Update: Partial<DamageEvidenceRow>;
        Relationships: [];
      };
    };
    Views: Record<string, never>;
    Functions: {
      accept_rental_invoice: {
        Args: { p_invoice_id: string };
        Returns: string;
      };
      provision_merchant_from_application: {
        Args: { p_application_id: string };
        Returns: string;
      };
      close_rental_contract: {
        Args: { p_contract_id: string };
        Returns: void;
      };
      lookup_renter_by_mobile: {
        Args: { p_mobile: string };
        Returns: Array<{
          id: string;
          has_nafath: boolean;
        }>;
      };
      confirm_renter_presence: {
        Args: { p_mobile: string; p_id_last4: string };
        Returns: Array<{
          id: string;
          full_name: string;
          mobile: string | null;
          city: string | null;
          has_nafath: boolean;
        }>;
      };
      get_renter_eligibility: {
        Args: { p_renter_id: string };
        Returns: Array<{
          user_id: string;
          limit_amount: number;
          used_amount: number;
          tier: EligibilityTier;
        }>;
      };
      record_contract_handover: {
        Args: { p_contract_id: string; p_photo_path: string };
        Returns: void;
      };
      record_rental_payment: {
        Args: { p_invoice_id: string };
        Returns: string;
      };
      record_nafath_signing: {
        Args: { p_note_id: string };
        Returns: void;
      };
      verify_and_activate_rental: {
        Args: { p_note_id: string };
        Returns: string;
      };
      record_identity_verification: {
        Args: { p_provider?: string; p_reference_id?: string | null };
        Returns: void;
      };
      next_invoice_number: { Args: Record<string, never>; Returns: string };
      next_contract_number: { Args: Record<string, never>; Returns: string };
      next_note_number: { Args: Record<string, never>; Returns: string };
      next_case_number: { Args: Record<string, never>; Returns: string };
    };
  };
};
