// Hand-typed surface of the AppLux Postgres schema, scoped to the
// entities Phase 2 actually reads/writes. We keep this narrow on purpose:
// once we have a stable Supabase project we can switch to types
// generated by `supabase gen types typescript`.
//
// Mirrors supabase/migrations/20260502120000_initial_schema.sql.

export type AppRole = 'customer' | 'merchant' | 'admin';
export type AccountStatus = 'pending' | 'active' | 'suspended';
export type MerchantApplicationStatus = 'pending' | 'approved' | 'rejected';
export type MerchantStatusDB = 'pending_review' | 'active' | 'suspended';
export type RentalCategoryDB = 'dress' | 'bag' | 'watch' | 'bisht';
export type EligibilityTier = 'standard' | 'premium' | 'elite';

export type LocalizedJson = { ar: string; en: string };

export type ProfileRow = {
  id: string;
  full_name: string;
  mobile: string | null;
  email: string | null;
  national_id: string | null;
  city: string | null;
  role: AppRole;
  account_status: AccountStatus;
  nafath_verified_at: string | null;
  created_at: string;
  updated_at: string;
};
export type ProfileInsert = Partial<ProfileRow> & { id: string; full_name: string };
export type ProfileUpdate = Partial<ProfileRow>;

export type RentalEligibilityRow = {
  user_id: string;
  limit_amount: number;
  used_amount: number;
  tier: EligibilityTier;
  assigned_by: string | null;
  assigned_at: string;
  notes: string | null;
  updated_at: string;
};
export type RentalEligibilityInsert = Partial<RentalEligibilityRow> & {
  user_id: string;
};
export type RentalEligibilityUpdate = Partial<RentalEligibilityRow>;

export type MerchantRow = {
  id: string;
  owner_user_id: string;
  application_id: string | null;
  company_name: string;
  commercial_reg_number: string;
  display_name: LocalizedJson;
  about: LocalizedJson | null;
  primary_category: RentalCategoryDB;
  city: string;
  verified: boolean;
  rating: number;
  rating_count: number;
  status: MerchantStatusDB;
  approved_at: string | null;
  approved_by: string | null;
  created_at: string;
  updated_at: string;
};
export type MerchantInsert = Partial<MerchantRow> & {
  owner_user_id: string;
  company_name: string;
  commercial_reg_number: string;
  display_name: LocalizedJson;
  primary_category: RentalCategoryDB;
  city: string;
};
export type MerchantUpdate = Partial<MerchantRow>;

export type MerchantApplicationRow = {
  id: string;
  applicant_user_id: string;
  company_name: string;
  commercial_reg_number: string;
  authorized_name: string;
  authorized_national_id: string;
  city: string;
  primary_category: RentalCategoryDB;
  contact_email: string | null;
  contact_phone: string | null;
  notes: string | null;
  status: MerchantApplicationStatus;
  decided_by: string | null;
  decided_at: string | null;
  decision_notes: string | null;
  submitted_at: string;
  created_at: string;
  updated_at: string;
};
export type MerchantApplicationInsert = Omit<
  MerchantApplicationRow,
  | 'id'
  | 'status'
  | 'decided_by'
  | 'decided_at'
  | 'decision_notes'
  | 'submitted_at'
  | 'created_at'
  | 'updated_at'
> & {
  status?: MerchantApplicationStatus;
};
export type MerchantApplicationUpdate = Partial<MerchantApplicationRow>;

// Minimal Database surface for typed supabase client. Add tables here as
// Phase 3+ wires in invoices, contracts, notes, damage cases, etc.
//
// Shape follows the GenericSchema contract from @supabase/postgrest-js
// (Tables/Views/Functions records, each table carrying Relationships).
export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: ProfileRow;
        Insert: ProfileInsert;
        Update: ProfileUpdate;
        Relationships: [];
      };
      rental_eligibility: {
        Row: RentalEligibilityRow;
        Insert: RentalEligibilityInsert;
        Update: RentalEligibilityUpdate;
        Relationships: [];
      };
      merchants: {
        Row: MerchantRow;
        Insert: MerchantInsert;
        Update: MerchantUpdate;
        Relationships: [];
      };
      merchant_applications: {
        Row: MerchantApplicationRow;
        Insert: MerchantApplicationInsert;
        Update: MerchantApplicationUpdate;
        Relationships: [];
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
  };
};
